.TH TRYTOND 1 "2012\-12\-15" "2.2" "Tryton Application Platform"

.SH NAME
trytond \- Tryton Application Platform (Server)

.SH SYNOPSIS
\fBtrytond\fR

.SH DESCRIPTION
Tryton is a high-level general purpose application platform written in Python and using PostgreSQL as database engine. It is the core base of an ERP.

.SH OPTIONS
\fBtrytond\fR has no options.

.SH FILES
\fB/etc/trytond.conf\fR

.SH SEE ALSO
\fItryton\fR(1)

.SH HOMEPAGE
More information about the Tryton server and the Tryton project can be found at <\fIhttp://www.tryton.org/\fR>.

.SH AUTHOR
Tryton server was written by the Tryton project <\fIhttp://www.tryton.org/\fR>.
.PP
This manual page was written by Daniel Baumann <\fIdaniel@debian.org\fR>.
