#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst

php_cf="/etc/yubico/val/config-db.php"
cfg_cf="/etc/yubico/val/config-db.cfg"

# PHP include
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=php:$php_cf
dbc_go yubikey-val $@

if [ `ykval-export-clients 2>/dev/null|grep -c ','` -eq 0 ]; then
    #No clients, create one
    ykval-gen-clients --urandom >/dev/null 2>&1 || true
fi

#Apache configuration
if [ "$1" = "configure" ] ; then
    CONF="yubikey-val"

    if [ -d /etc/apache2/conf-available ] && [ ! -e /etc/apache2/conf-available/$CONF.conf ]; then
        ln -s ../../yubico/val/apache.conf /etc/apache2/conf-available/$CONF.conf
    fi

    COMMON_STATE=$(dpkg-query -f '${Status}' -W 'apache2.2-common' 2>/dev/null | awk '{print $3}' || true)
    if [ -e /usr/share/apache2/apache2-maintscript-helper ] ; then
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_invoke enconf $CONF || exit $?
    elif [ "$COMMON_STATE" = "installed" ] || [ "$COMMON_STATE" = "unpacked" ] ; then
        if [ -d /etc/apache2/conf.d/ -a ! -L /etc/apache2/conf.d/$CONF.conf ]; then
            ln -s ../conf-available/$CONF.conf /etc/apache2/conf.d/$CONF.conf
	fi
    fi

    if [ -f /etc/init.d/apache2 ] ; then
        if [ -x /usr/sbin/invoke-rc.d ]; then
            invoke-rc.d apache2 reload 3>/dev/null || true
        else
            /etc/init.d/apache2 reload 3>/dev/null || true
        fi
    fi
fi

#DEBHELPER#

exit 0
