#!/bin/sh
### BEGIN INIT INFO
# Provides:          ardukey-auth
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ArduKey authentication service.
### END INIT INFO

DAEMON="/usr/sbin/ardukey-auth.py"
NAME="ardukey-auth"
PIDFILE="/var/run/ardukey-auth.pid"

## Define LSB log_* functions.
## Note: Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

case "${1}" in

    start)
        log_daemon_msg "Starting ArduKey authentication service" "${NAME}"
        start-stop-daemon --start --make-pidfile --pidfile "${PIDFILE}" --background --exec "${DAEMON}"

        if ( test "${?}" = 0 ); then
           log_end_msg 0
        else
           log_end_msg 1
           rm -f "${PIDFILE}"
           exit 1
        fi
    ;;

    stop)
        log_daemon_msg "Stopping ArduKey authentication service" "${NAME}"

        if ( ! test -f "${PIDFILE}" ); then
           log_end_msg 1
           log_failure_msg "${NAME} is not running"
           exit 1
        fi

        start-stop-daemon --stop --quiet --oknodo --pidfile "${PIDFILE}"

        if ( test "${?}" = 0 ); then
           rm -f "${PIDFILE}"
           log_end_msg 0
        else
           log_end_msg 1
           exit 1
        fi
    ;;

    restart)
        ${0} stop && sleep 2 && ${0} start
    ;;

    status)
        status_of_proc -p "${PIDFILE}" "${DAEMON}" "${NAME}" 2>/dev/null
        exit ${?}
    ;;

    *)
        log_action_msg "Usage: ${0} { start | stop | restart | status }"
        exit 2
    ;;

esac

exit 0
