.TH ardukey-auth-conf "1" "January 2014" "" "ArduKey authserver"

.SH NAME
\fBardukey-auth-conf\fP - ArduKey authserver configuration tool

.SH SYNOPSIS
.nf
.fam C
\fBardukey-auth-conf\fP [\fIoptions\fP]
.fam T
.fi

.SH DESCRIPTION
\fBardukey-auth-conf\fP allows to manage the ArduKey authserver. You can
add/revoke ArduKey devices or generate/revoke API keys that are required to
communicate with this server. Of course, you can list all available information.

.SH OPTIONS
.TP
.B
\fB--list-ardukeys\fR
Lists all available ArduKeys.

.TP
.B
\fB--add-ardukey\fR \fIPUBLICID\fP \fISECRETID\fP \fIAESKEY\fP
Adds a new ArduKey.

.TP
.B
\fB--revoke-ardukey\fR \fIPUBLICID\fP
Revokes an ArduKey.

.TP
.B
\fB--delete-ardukey\fR \fIPUBLICID\fP
Deletes an ArduKey.

.TP
.B
\fB--list-apikeys\fR
Lists all available API keys.

.TP
.B
\fB--generate-apikey\fR
Generates a new API key.

.TP
.B
\fB--revoke-apikey\fR \fIAPIID\fP
Revokes an API key.

.TP
.B
\fB--version, \fB-v\fR
Prints version and exits.

.TP
.B
\fB--help\fR, \fB-h\fR
Show summary of options.
.PP

.SH FILES
/etc/ardukey-auth-server.conf

.SH AUTHOR
Bastian Raschke <bastian.raschke@posteo.de>

.SH BUGS
Please send bug reports above author mail address.

.SH "SEE ALSO"
Visit https://sicherheitskritisch.de for more interesting projects.
