.TH ardukey-auth-conf "1" "June 2015" "" "ArduKey auth server"

.SH NAME
\fBardukey-auth-conf\fP - ArduKey auth server configuration tool

.SH SYNOPSIS
.nf
.fam C
\fBardukey-auth-conf\fP [\fIoptions\fP]
.fam T
.fi

.SH DESCRIPTION
\fBardukey-auth-conf\fP allows to manage the ArduKey auth server. You can
add/revoke ArduKey devices or generate/revoke API keys that are required to
communicate with this server. Of course, you can list all available information.

.SH OPTIONS
.TP
.B
\fB--list-ardukeys\fR
List all available ArduKeys.

.TP
.B
\fB--add-ardukey\fR \fIPUBLICID\fP \fISECRETID\fP \fIAESKEY\fP
Add a new ArduKey.

.TP
.B
\fB--revoke-ardukey\fR \fIPUBLICID\fP
Revoke an ArduKey.

.TP
.B
\fB--delete-ardukey\fR \fIPUBLICID\fP
Delete an ArduKey.

.TP
.B
\fB--list-apikeys\fR
List all available API keys.

.TP
.B
\fB--generate-apikey\fR
Generate a new API key.

.TP
.B
\fB--revoke-apikey\fR \fIAPIID\fP
Revoke an API key.

.TP
.B
\fB--version, \fB-v\fR
Print version and exit.

.TP
.B
\fB--help\fR, \fB-h\fR
Show summary of options.
.PP

.SH FILES
/etc/ardukey-auth-server.conf

.SH AUTHOR
Bastian Raschke <bastian.raschke@posteo.de>

.SH BUGS
Please send bug reports above author mail address.

.SH "SEE ALSO"
Visit https://sicherheitskritisch.de for more interesting projects.
